<h2>Sign up using this form</h2>
<?php echo "<p>".$this->response->getContent()."</p>"; ?>
<?php echo $this->tag->form("signup/index"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->textField("password"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Register");?>
    </p>

</form>
<?php echo $this->tag->linkTo(['index','back',"class" => "btn btn-primary"]);